imports:
  - { resource: 'parameters.yml' }
  - { resource: 'security.yml' }
  - { resource: 'services.yml' }
  - { resource: 'app.yml' }

parameters:
  locale: en
  handlebars.helper_interface.class: JaySDe\HandlebarsBundle\Helper\HelperInterface
  handlebars.helper_interface.method: handle

framework:
  secret: "%env(SECRET_TOKEN)%"
  router:
    resource: "%kernel.root_dir%/config/routing.yml"
    strict_requirements: ~
  templating:
    engines: ['twig', 'handlebars']
  form: ~
  csrf_protection: { enabled: true }
  assets:
    base_path: /assets/
  default_locale: "%locale%"
  session:
    name: sunrise_session
    save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
  translator:
    paths:
    - "%kernel.root_dir%/../vendor/commercetools/sunrise-theme/translations"
twig:
  debug: "%kernel.debug%"
  strict_variables: "%kernel.debug%"
handlebars:
  cms:
    default_namespace: cms
  translation:
    default_namespace: main
    interpolation_prefix: __
    interpolation_suffix: __
  paths:
    - "%kernel.root_dir%/Resources/views"
    - "%kernel.root_dir%/../vendor/commercetools/sunrise-theme/templates"
commercetools:
  cache:
    category: true
    product_type: true
    product: true
  credentials:
    client_id: "%env(CTP_CLIENT_ID)%"
    client_secret: "%env(CTP_CLIENT_SECRET)%"
    project: "%env(CTP_PROJECT)%"
  defaults:
    country: DE
  fallback_languages:
    de:
    - en
    en:
    - de
  facets:
    categories:
      hierarchical: true
      type: categories
    color: ~
    size:
      field: commonSize
    brand:
      field: designer
      display: list
  currency:
    DE: EUR
    UK: GBP
